spring:
  datasource:
    url: jdbc:h2:mem:testdb:PUBLIC;DB_CLOSE_ON_EXIT=false
    username: sa
    password: password
    driverClassName: org.h2.Driver

  spring:
    jpa:
      database-platform: org.hibernate.dialect.H2Dialect
      properties:
        hibernate:
          show_sql: true
          format_sql: true
      hibernate:
        ddl-auto: none


